"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Eshaan Singh and Advay Vyas, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: es45858
UT EID 2: av37899
"""



def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    combo = []
    for i in range(len(s)):
        for j in range(i+1, len(s)+1):
            combo.append(s[i:j])
    largest = ""
    for i in combo:
        if len(set(i)) == len(i) and len(largest) < len(i):
            largest = i
    return len(largest)

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    n = len(s)
    for i in range(n):
        freq = {}
        dupes = False
        curr = 0
        for j in range(i, n):
            if s[j] in freq:
                dupes = True
            freq[s[j]] = freq.get(s[j], 0) + 1
            if not dupes:
                curr += 1
                max_length = max(max_length, curr)
    return max_length





def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    freq = {}
    left = 0
    right = 0
    max_len = 0
    while right < len(s):
        if s[right] in freq:
            del freq[s[left]]
            left +=1
        else:
            freq[s[right]] = 1
            max_len = max(max_len, right - left + 1)
            right += 1
    return max_len
